M48
; DRILL file {KiCad 7.0.10} date Wed Apr 17 19:05:41 2024
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-04-17T19:05:41-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.10
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0866
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
%
G90
G05
T1
X2.55Y-3.2
X2.55Y-4.25
X3.35Y-3.2
X3.35Y-4.25
T2
X0.1969Y-0.1969
X0.1969Y-5.5118
X3.7402Y-0.1969
X3.7402Y-5.5118
M30
